//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanMan.SharedLocalization.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedLocalizerService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedLocalizerService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinanMan.SharedLocalization.Resources.Localization.SharedLocalizerService", typeof(SharedLocalizerService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Automated Realms.
        /// </summary>
        public static string AboutAutomatedRealms {
            get {
                return ResourceManager.GetString("AboutAutomatedRealms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string AccountColumnHeader {
            get {
                return ResourceManager.GetString("AccountColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account:.
        /// </summary>
        public static string AccountNameRowHeader {
            get {
                return ResourceManager.GetString("AccountNameRowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Summary.
        /// </summary>
        public static string AccountSummary {
            get {
                return ResourceManager.GetString("AccountSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        public static string AccountType {
            get {
                return ResourceManager.GetString("AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Account.
        /// </summary>
        public static string AddAccount {
            get {
                return ResourceManager.GetString("AddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted Balance.
        /// </summary>
        public static string AdjustedBalance {
            get {
                return ResourceManager.GetString("AdjustedBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string AmountColumnHeader {
            get {
                return ResourceManager.GetString("AmountColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount:.
        /// </summary>
        public static string AmountRowHeader {
            get {
                return ResourceManager.GetString("AmountRowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearFilter.
        /// </summary>
        public static string ClearFilter {
            get {
                return ResourceManager.GetString("ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Sort.
        /// </summary>
        public static string ClearSort {
            get {
                return ResourceManager.GetString("ClearSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the Thing?.
        /// </summary>
        public static string ConfirmMarkDeleteTitle {
            get {
                return ResourceManager.GetString("ConfirmMarkDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Pending?.
        /// </summary>
        public static string ConfirmMarkPendingTitle {
            get {
                return ResourceManager.GetString("ConfirmMarkPendingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Buttons.
        /// </summary>
        public static string ControlButtonsColumnHeader {
            get {
                return ResourceManager.GetString("ControlButtonsColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Values.
        /// </summary>
        public static string CoreValues {
            get {
                return ResourceManager.GetString("CoreValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Balance.
        /// </summary>
        public static string CurrentBalance {
            get {
                return ResourceManager.GetString("CurrentBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current record information:.
        /// </summary>
        public static string CurrentRecordInformationText {
            get {
                return ResourceManager.GetString("CurrentRecordInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Entry.
        /// </summary>
        public static string DataEntry {
            get {
                return ResourceManager.GetString("DataEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        public static string Deposit {
            get {
                return ResourceManager.GetString("Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposits.
        /// </summary>
        public static string Deposits {
            get {
                return ResourceManager.GetString("Deposits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Transaction.
        /// </summary>
        public static string EditTransaction {
            get {
                return ResourceManager.GetString("EditTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EditTransactionInstructions {
            get {
                return ResourceManager.GetString("EditTransactionInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Posted Date.
        /// </summary>
        public static string EnterPostedDateTitle {
            get {
                return ResourceManager.GetString("EnterPostedDateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your username or password?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string GetStartedButtonText {
            get {
                return ResourceManager.GetString("GetStartedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Cool Way.
        /// </summary>
        public static string HeroSubtitle {
            get {
                return ResourceManager.GetString("HeroSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Your Financials.
        /// </summary>
        public static string HeroTitle {
            get {
                return ResourceManager.GetString("HeroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Management Tracker.
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Transaction Type.
        /// </summary>
        public static string InvalidTransactionTypeMessage {
            get {
                return ResourceManager.GetString("InvalidTransactionTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Item Controls.
        /// </summary>
        public static string LineItemControlColumnHeader {
            get {
                return ResourceManager.GetString("LineItemControlColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Item Type.
        /// </summary>
        public static string LineItemType {
            get {
                return ResourceManager.GetString("LineItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Managment.
        /// </summary>
        public static string ListManagement {
            get {
                return ResourceManager.GetString("ListManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Management.
        /// </summary>
        public static string ListManagementTitleDisplay {
            get {
                return ResourceManager.GetString("ListManagementTitleDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup Lists.
        /// </summary>
        public static string LookupListTitle {
            get {
                return ResourceManager.GetString("LookupListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this transaction record?.
        /// </summary>
        public static string MarkDeletedQuestion {
            get {
                return ResourceManager.GetString("MarkDeletedQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to mark this transaction as Pending?  This will remove the Posted Date from the record..
        /// </summary>
        public static string MarkPendingQuestion {
            get {
                return ResourceManager.GetString("MarkPendingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo.
        /// </summary>
        public static string MemoColumnHeader {
            get {
                return ResourceManager.GetString("MemoColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo:.
        /// </summary>
        public static string MemoRowHeader {
            get {
                return ResourceManager.GetString("MemoRowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No accounts have been added..
        /// </summary>
        public static string NoAccountsMessage {
            get {
                return ResourceManager.GetString("NoAccountsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items to display.
        /// </summary>
        public static string NoItemsMessage {
            get {
                return ResourceManager.GetString("NoItemsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Sort.
        /// </summary>
        public static string NoSortText {
            get {
                return ResourceManager.GetString("NoSortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there&apos;s nothing at this address..
        /// </summary>
        public static string NothingAtAddress {
            get {
                return ResourceManager.GetString("NothingAtAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No transactions have been entered.
        /// </summary>
        public static string NoTransactionsMessage {
            get {
                return ResourceManager.GetString("NoTransactionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Date.
        /// </summary>
        public static string OpenDate {
            get {
                return ResourceManager.GetString("OpenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay To.
        /// </summary>
        public static string PayeeColumnHeader {
            get {
                return ResourceManager.GetString("PayeeColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payee:.
        /// </summary>
        public static string PayeeRowHeader {
            get {
                return ResourceManager.GetString("PayeeRowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        public static string Payments {
            get {
                return ResourceManager.GetString("Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string PendingColumnHeader {
            get {
                return ResourceManager.GetString("PendingColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan your savings for future spending.
        /// </summary>
        public static string PlanBodyContent {
            get {
                return ResourceManager.GetString("PlanBodyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string PlanHeader {
            get {
                return ResourceManager.GetString("PlanHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted Date.
        /// </summary>
        public static string PostedDateLabel {
            get {
                return ResourceManager.GetString("PostedDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need an account? Sign up..
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Ascending.
        /// </summary>
        public static string SortAscending {
            get {
                return ResourceManager.GetString("SortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Descending.
        /// </summary>
        public static string SortDescending {
            get {
                return ResourceManager.GetString("SortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Info:.
        /// </summary>
        public static string SortInfoLabel {
            get {
                return ResourceManager.GetString("SortInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Balance.
        /// </summary>
        public static string StartingBalance {
            get {
                return ResourceManager.GetString("StartingBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string TotalRowHeader {
            get {
                return ResourceManager.GetString("TotalRowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track your financial accounts and the related transactions and balances.
        /// </summary>
        public static string TrackBodyContent {
            get {
                return ResourceManager.GetString("TrackBodyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        public static string TrackHeader {
            get {
                return ResourceManager.GetString("TrackHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction History.
        /// </summary>
        public static string TransactionHistory {
            get {
                return ResourceManager.GetString("TransactionHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A listing of transaction history items..
        /// </summary>
        public static string TransactionHistoryTableDescription {
            get {
                return ResourceManager.GetString("TransactionHistoryTableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Date.
        /// </summary>
        public static string TransDateColumnHeader {
            get {
                return ResourceManager.GetString("TransDateColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Date:.
        /// </summary>
        public static string TransDateRowHeader {
            get {
                return ResourceManager.GetString("TransDateRowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfers.
        /// </summary>
        public static string Transfers {
            get {
                return ResourceManager.GetString("Transfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch your money grow (or shrink if you don’t manage it well...which you should since you’re using this app!).
        /// </summary>
        public static string WatchBodyContent {
            get {
                return ResourceManager.GetString("WatchBodyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch.
        /// </summary>
        public static string WatchHeader {
            get {
                return ResourceManager.GetString("WatchHeader", resourceCulture);
            }
        }
    }
}
